# Generated by Django 4.0.6 on 2022-10-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_adress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
