# Generated by Django 4.0.6 on 2022-11-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address_order_status_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date',)},
        ),
    ]
