# Generated by Django 4.0.6 on 2022-10-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='status',
            name='not_available',
        ),
        migrations.AddField(
            model_name='status',
            name='availability',
            field=models.CharField(blank=True, choices=[('in_stock', 'в наличии'), ('not_in_stock', 'нет на складе')], max_length=20, null=True, verbose_name='Наличие'),
        ),
    ]
