# Generated by Django 4.0.6 on 2022-10-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_status_in_stock_remove_status_not_available_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
