# Generated by Django 4.0.6 on 2022-10-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_category_hand_tool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория товара'),
        ),
    ]
